spring:
  datasource:
    #    url: jdbc:p6spy:mysql://127.0.0.1:3306/psychological_evaluation_sys?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    #    username: root
    #    password: 123456
#    url: jdbc:p6spy:mysql://211.149.238.91:3306/psysys?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:p6spy:mysql://45.205.1.240:3306/accounting?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Everglow@2020
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  devtools:
    restart:
      enabled: true
      quiet-period: 200ms
      poll-interval: 1s







